<?php
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get('Zkood\CartInformation\Helper\Data'); 
if($helper->isEnabled()){
	if(!$helper->disableGuest()){
 ?>
	   <input class="custom-button" type="button" value="generatecsvbutton">
	<?php 
	}elseif($helper->isEnabled()){
		$isLoggedin = $block->getLogin();
		if($isLoggedin) { ?>
			<input class="custom-button" type="button" value="generatecsvbutton" onclick="location.href='/cartinfo/Export/CartInfo'">
		<?php
		}
	}
}
?>
